name: Build mrs file
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download shell script
      run: wget https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh

    - name: Make the script executable
      run: chmod +x gfwlist2dnsmasq.sh

    - name: Get the gfwlist
      run: |
        ./gfwlist2dnsmasq.sh -l -o gfwlist.list
        sed -i 's/^/+./' gfwlist.list

    - name: Get cloudflare ipv4 address
      run: curl -sSL https://www.cloudflare-cn.com/ips-v4 -o cloudflare.list
      
    - name: Download pre-release mihomo
      run: |
        download_url=$(curl -sSL https://api.github.com/repos/MetaCubeX/mihomo/releases | grep "mihomo-linux-amd64-alpha" | grep ".gz" | grep "browser_download_url" | cut -d '"' -f 4)
        curl -sSL ${download_url} -o mihomo.gz
        gzip -d mihomo.gz
        
    - name: Convert to mrs file
      run: |
        chmod +x mihomo
        ./mihomo convert-ruleset domain text gfwlist.list gfwlist.mrs
        ./mihomo convert-ruleset ipcidr text cloudflare.list cloudflare.mrs

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit and push
      run: |
        git checkout -b mrs
        git add gfwlist.mrs
        git add cloudflare.mrs
        git commit -m "Update processed file"
        git push -f origin mrs
